import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Counter } from "@/components/counter";
import { Mirror } from "@/components/mirror";

import CountProvider from "@/context/Count";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>useContext</h1>

        <CountProvider>
          <h1>YouTube DevALMO, useContext</h1>

          <Counter />

          <hr />

          <Mirror />
        </CountProvider>
      </main>
    </>
  );
}
